### PR TITLE
set existing customers to approved

### PR DESCRIPTION
**Pull request by taoufiqaitali**
when installing module, existing customers set as not approved so they cant logged in

this change will set existing customers as approved

### CODE REVIEW

**Comment by amitshree** [comment]
Thank you for your contribution @taoufiqaitali .

Regarding approving all existing customers account, I think this control should be given to admin user(s). Admin might want to approve existing customer accounts or admin might want their accounts to remain un-approved and approve them one-by-one.

A new section can be developed in admin panel using which admin can either approve or un-approve all customers. 

Let me know your thoughts.

**Comment by taoufiqaitali** [comment]
i think exisitng customers should be approved automatic,(we had same case in our company when i use this extension)

**this option can be added separately** 
maybe add option in action for bulk approve/unapprove customers, like subscribe and unsubscribe to newsletter
image

i will try develop this function and create another pull request

**Comment by amitshree** [comment]
> i will try develop this function and create another pull request
Sure. Sounds good :)

**Comment by amitshree** [comment]
> i will try develop this function and create another pull request

Sure. Sounds good :+1:

**Comment by gewaechshaus** [comment]
@taoufiqaitali - did you already start writing the mass action part? Sounds like a good idea! 

Cheers
Jan

**Comment by taoufiqaitali** [comment]
> @taoufiqaitali - did you already start writing the mass action part? Sounds like a good idea!
> 
> Cheers
> Jan

yeah i'm working on this 
image

**Comment by taoufiqaitali** [comment]
@amitshree @gewaechshaus  new function is added in pull request #17 
2 files added and 1 file edited to add this option

**Comment by amitshree** [comment]
Thanks @taoufiqaitali . I have merged it.

**Comment by gewaechshaus** [comment]
Wow @taoufiqaitali & @amitshree - that was real fast. Thanks a million!

**Pull request merged**
